_BASE_: "kitti-nasfpn.yaml"
MODEL:
  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 10
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
  PIXEL_MEAN: [93.79843106, 98.72519928, 95.84587936]
  PIXEL_STD: [85.06779396, 85.94050764, 87.22792189]
INPUT:
  MIN_SIZE_TRAIN: (320, 500)
  # MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MIN_SIZE_TEST: 370
  FORMAT: "RGB"
DATASETS:
  TRAIN: ('voc_2012_trainval',)
  TEST: ('voc_2012_test',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 10000
  WARMUP_ITERS: 10
  GAMMA: 0.01
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
TEST:
  EVAL_PERIOD: 3000
  PRECISE_BN:
    ENABLED: True