_BASE_: "../Base-RCNN-NASFPN.yaml"
MODEL:
  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest50_detectron-255b5649.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  NASFPN:
    NORM: "SyncBN"
    STACK_NUM: 1
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 32
    NUM_CLASSES: 10
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
  PIXEL_MEAN: [93.79843106, 98.72519928, 95.84587936]
  PIXEL_STD: [85.06779396, 85.94050764, 87.22792189]
INPUT:
  MIN_SIZE_TRAIN: (320, 380)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MIN_SIZE_TEST: 370
  FORMAT: "RGB"
DATASETS:
  TRAIN: ('voc_2012_trainval',)
  TEST: ('voc_2012_test',)
SOLVER:
  STEPS: (6000, 8000, 12000,)
  MAX_ITER: 15000
  WARMUP_ITERS: 10
  GAMMA: 0.01
  IMS_PER_BATCH: 6
  BASE_LR: 0.02
TEST:
  EVAL_PERIOD: 1000
  PRECISE_BN:
    ENABLED: True
