# This yaml serves as base of other yaml
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 10
INPUT:
  MIN_SIZE_TRAIN: 0  # 0 disable resize
  MIN_SIZE_TEST: 0  # 0 disable resize
DATASETS:
  TRAIN: ('voc_2012_trainval',)
  TEST: ('voc_2012_test',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 1000
  WARMUP_ITERS: 10
  GAMMA: 0.01
  IMS_PER_BATCH: 16
  BASE_LR: 0.005
TEST:
  EVAL_PERIOD: 0  # eval the model during training, 0 to disable
