_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1333
  FORMAT: "RGB"
DATASETS:
  TRAIN: ('voc_2012_trainval',)
  TEST: ('voc_2012_test',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 1000
  WARMUP_ITERS: 10
  GAMMA: 0.01
  IMS_PER_BATCH: 16
  BASE_LR: 0.005
TEST:
  PRECISE_BN:
    ENABLED: True