_BASE_: "kitti.yaml"
OUTPUT_DIR: './output/small_test/'
# MODEL:
#   WEIGHTS: "./output/resnest_101_cyclist_lr_005/model_final.pth"
DATASETS:
  TRAIN: ('tsinghua_cyclist_small_train',)  # tsinghua_cyclist_small_train, tsinghua_cyclist_train
  TEST: ('tsinghua_cyclist_small_val',)     # tsinghua_cyclist_small_val, tsinghua_cyclist_val
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 40
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 2
  BASE_LR: 0.005