_BASE_: "kitti-faster-rcnn-101.yaml"
# MODEL:
#   WEIGHTS: "./output/model_final.pth"
DATASETS:
  TRAIN: ('tsinghua_cyclist_train',)  # tsinghua_cyclist_small_train, tsinghua_cyclist_train
  TEST: ('tsinghua_cyclist_val',)     # tsinghua_cyclist_small_val, tsinghua_cyclist_val
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 15000
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
TEST:
  EVAL_PERIOD: 3000  # eval the model during training, 0 to disable
  