_BASE_: "kitti-faster-rcnn-resnest-101.yaml"
OUTPUT_DIR: './output/'
MODEL:
  PIXEL_MEAN: [73.10043784, 80.65596148, 65.41796925]
  PIXEL_STD: [45.07742417, 46.2616377, 42.94827095]
  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth"
DATASETS:
  TRAIN: ('tsinghua_cyclist_train',)  # tsinghua_cyclist_small_train, tsinghua_cyclist_train
  TEST: ('tsinghua_cyclist_val',)     # tsinghua_cyclist_small_val, tsinghua_cyclist_val
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 10000
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 2
  BASE_LR: 0.02
TEST:
  EVAL_PERIOD: 2000  # eval the model during training, 0 to disable

###
# validation set:
# Easy Mod. Hard
# 84.05 74.20 73.61
# test set:
# 77.5200,67.2800,65.2000